var tickets = [    
  {   "model":"Jan 22, 2018",
      "city":"Saskatoon", 
      "photoLocation":"img/tickets.jpg",
      "price":"54.99"},   
  {   "model":"Feb 17, 2018", 
      "city":"Regina",
      "photoLocation":"img/tickets.jpg",
      "price":"49.99"},
  {   "model":"Feb 25, 2018", 
      "city":"Prince Albert",
      "photoLocation":"img/tickets.jpg",
      "price":"39.99"},    
  {   "model":"March 9, 2018", 
      "city":"North Battleford",
      "photoLocation":"img/tickets.jpg",
      "price":"29.99"},
  {   "model":"March 21, 2018", 
      "city":"Lloydminster",
      "photoLocation":"img/tickets.jpg",
      "price":"25.99"},
  {   "model":"March 30, 2018", 
      "city":"Yorkton",
      "photoLocation":"img/tickets.jpg",
      "price":"34.99"},
  {   "model":"April 10, 2018", 
      "city":"Kindersly",  
      "photoLocation":"img/tickets.jpg",
      "price":"39.99"},  
  {   "model":"April 24, 2018", 
      "city":"Wynyard",
      "photoLocation":"img/tickets.jpg",
      "price":"44.99"},
];


