var merch = [    
  {   "model":"Outskirts T-Shirt",
      "description":"Outskirts: Self Titled", 
      "photoLocation":"img/outskirtsLogo.png", 
      "price":24.99},      
  {   "model":"Life T-Shirt", 
      "description":"Life T-Shirt",
      "photoLocation":"img/life.png", 
      "price":24.99},
  {   "model":"Zero Gravity T-Shirt",
      "description":"Zero Gravity T-Shirt", 
      "photoLocation":"img/zerogravity.png", 
      "price":24.99},      
  {   "model":"Rise Up T-Shirt", 
      "description":"Rise Up T-Shirt",
      "photoLocation":"img/riseup.png", 
      "price":24.99},
  {   "model":"Outskirts Beanie", 
      "description":"Outskirts Beanie",
      "photoLocation":"img/beanie.jpg", 
      "price":24.99},
  {   "model":"Outskirts Tote Bag", 
      "description":"Outskirts Tote Bag",
      "photoLocation":"img/tote.jpg", 
      "price":24.99},
  {   "model":"Outskirts Socks", 
      "description":"Outskirts Socks",
      "photoLocation":"img/socks.jpg", 
      "price":24.99},
  {   "model":"Outskirts Pullover", 
      "description":"Outskirts Pullover",
      "photoLocation":"img/pullover.jpg", 
      "price":24.99},
];
